



server.port=${PORT:9191}
server.port=9191
eureka.client.service-url.defaultZone=https://protective-determination-production.up.railway.app/eureka/

# Gateway routes
# Gateway route for LOGIN-SERVICE without load balancing
spring.cloud.gateway.routes[0].id=LOGIN-SERVICE
spring.cloud.gateway.routes[0].uri=https://spirited-liberation-production-0153.up.railway.app
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/login/**
spring.cloud.gateway.routes[0].filters[0]=RemoveRequestHeader=Authorization

# Protect all other services with JWT authentication
spring.cloud.gateway.routes[1].id=MEMBERS-SERVICE
spring.cloud.gateway.routes[1].uri=https://strong-alignment-production.up.railway.app
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/members/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[1].filters[1]=AddRequestHeader=X-Requested-By, MyApiGateway



spring.cloud.gateway.routes[2].id=DOCUMENTS-SERVICE
spring.cloud.gateway.routes[2].uri=lb://DOCUMENTS-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/files/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[2].filters[1]=AddRequestHeader=X-Requested-By, MyApiDocument

spring.cloud.gateway.routes[3].id=EVENTS-SERVICE
spring.cloud.gateway.routes[3].uri=lb://EVENTS-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/events/**
spring.cloud.gateway.routes[3].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[3].filters[1]=AddRequestHeader=X-Requested-By, MyApiEvents

spring.cloud.gateway.routes[4].id=HARVEST-SERVICE
spring.cloud.gateway.routes[4].uri=lb://HARVEST-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/harvest/**
spring.cloud.gateway.routes[4].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[4].filters[1]=AddRequestHeader=X-Requested-By, MyApiHarvest

spring.cloud.gateway.routes[5].id=THANKSGIVING-SERVICE
spring.cloud.gateway.routes[5].uri=lb://THANKSGIVING-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/thanksGiving/**
spring.cloud.gateway.routes[5].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[5].filters[1]=AddRequestHeader=X-Requested-By, MyApiThanksgiving

spring.cloud.gateway.routes[6].id=PARISH-SERVICE
spring.cloud.gateway.routes[6].uri=lb://PARISH-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/parish/**
spring.cloud.gateway.routes[6].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[6].filters[1]=AddRequestHeader=X-Requested-By, MyApiParish
# Global CORS configuration
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=Content-Type,Authorization
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true


# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.root=INFO
logging.level.org.springframework.http=DEBUG
logging.level.org.springframework.cloud.gateway.filter=DEBUG
logging.level.org.springframework.cloud.gateway.route=DEBUG
logging.level.org.springframework.cloud.gateway.handler=DEBUG
logging.level.io.netty=DEBUG



